# Generated by Django 4.2.6 on 2023-11-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIEAB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idNumber',
            field=models.CharField(default='None', max_length=8),
        ),
    ]
