# Generated by Django 5.0.1 on 2024-06-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIEAB', '0003_bookingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservationTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='0', max_length=1)),
                ('nine', models.BooleanField(default=False)),
                ('nine_thirty', models.BooleanField(default=False)),
                ('ten', models.BooleanField(default=False)),
                ('ten_thirty', models.BooleanField(default=False)),
                ('eleven', models.BooleanField(default=False)),
                ('eleven_thirty', models.BooleanField(default=False)),
                ('twelve', models.BooleanField(default=False)),
                ('twelve_thirty', models.BooleanField(default=False)),
                ('one', models.BooleanField(default=False)),
                ('one_thirty', models.BooleanField(default=False)),
                ('two', models.BooleanField(default=False)),
                ('two_thirty', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('three_thirty', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('four_thirty', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
            ],
        ),
    ]
