# Generated by Django 5.0.1 on 2024-06-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIEAB', '0004_reservationtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtimes',
            name='room_id',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
