# Generated by Django 5.0.1 on 2024-06-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIEAB', '0005_alter_reservationtimes_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIEAB.bookingroom')),
            ],
        ),
        migrations.DeleteModel(
            name='reservationTimes',
        ),
    ]
