# Generated by Django 5.0.1 on 2024-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIEAB', '0002_userprofile_idnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(default='0', max_length=3)),
                ('room', models.CharField(default='None', max_length=255, unique=True)),
            ],
        ),
    ]
